#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Mar 21 02:15:49 2019

@author: yangyutu123
"""

import matplotlib.pyplot as plt
import numpy as np

data1 = np.genfromtxt('testY.txt')
data2 = np.genfromtxt('prediction.txt')

plt.close('all')
plt.figure(1)
plt.scatter(data1[:,0], data2[:,0])
plt.xlabel('true value Rg')
plt.ylabel('prediction value Rg')
plt.savefig('RgError.png')

plt.figure(2)
plt.scatter(data1[:,1], data2[:,1])
plt.xlabel('true value psi6')
plt.ylabel('prediction value psi6')
plt.savefig('Psi6Error.png')